_VIBECHECK_DIR="${${(%):-%x}:A:h}"

based() {
  local phrases=(
    "BASED"
    "Dude.... it was super BASED"
    "Absolutely BASED, no notes"
    "BASED behavior detected"
    "That's the most BASED thing I've ever seen"
    "Ultra BASED. Respect."
    "BASED af bro"
    "Certified BASED moment"
    "We don't deserve this level of BASED"
    "BASED energy only in this house"
    "Historically BASED"
    "The BASED has been doubled"
    "Maximum BASED achieved"
    "Sir, this is extremely BASED"
    "BASED status: confirmed by kernel audit"
    "Warning: BASED overflow detected"
    "System integrity improved by BASED injection"
    "BASED.exe has stopped questioning reality"
    "Compile successful. Output: BASED"
    "The Council has reviewed this and deemed it BASED"
    "BASED clearance level: Omega"
    "This action has been archived under BASED jurisprudence"
    "Official classification: BASED (uncontested)"
    "BASED detected in quantum superposition"
    "You have unlocked: BASED DLC (uninstallable)"
    "Reality lag detected… syncing BASED"
    "BASED spawned outside simulation boundaries"
    "ERROR: too BASED for rendering pipeline"
    "being BASED is not a privilege. It's a responsibility."
    "Your ancestors are smiling at you. BASED."
    "BASED level: peer-reviewed and published"
    "Achievement unlocked: Did something BASED while nobody was watching"
    "The gigachad inside you has awakened"
    "Philosophers have debated this for centuries. Conclusion: BASED"
    "FBI has opened a file on this level of BASED"
    "Local man too BASED to be contained by zip code"
    "BASED so hard the universe had to patch itself"
    "BASED: successfully merged into main without conflicts"
    "Sudo not required for this level of BASED"
    "Your PATH leads directly to BASED city"
    "404: Cringe not found. Result: BASED"
    "Garbage collection skipped: object is too BASED to delete"
    "BASED intensity at 11ty percent"
    "Architecturally BASED and modularly sound"
  )
  
  print -P "\n%B%F{144}>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> $msg%f%b" | pv -qL 100
  [[ -f "$_VIBECHECK_DIR/ascii/gigachad.txt" ]] && cat "$_VIBECHECK_DIR/ascii/gigachad.txt"
  echo "${phrases[$((RANDOM % ${#phrases[@]} + 1))]}"
  
}

cringe() {
  local phrases=(
    "CRINGE: Validation failed (Reason: L-take)"
    "Segmentation fault in your social hierarchy"
    "Dependency error: missing father figure"
    "Oof. High-latency interaction detected"
    "CRINGE status: Persisted to disk"
    "My kernel just panicked looking at this"
    "Yikes. Adding this to the technical debt pile"
    "Your PR has been rejected. Reason: Absolute Cringe"
    "Even Gemini wouldn't generate this"
    "Legacy behavior detected. Initiating self-destruct"
    "CRINGE detected in syscall trace"
    "Kernel downgrade recommended"
    "Process terminated by collective secondhand embarrassment"
    "Unhandled exception: social misalignment"
    "RuntimeWarning: cringe overflow imminent"
    "Garbage collector refused to clean this"
    "The Council has unanimously voted: CRINGE"
    "This has been classified as inadmissible in all known timelines"
    "Archived under: DO NOT REFERENCE AGAIN"
    "Interdimensional review board denied existence of this action"
    "Your reputation has been de-indexed"
    "Reality buffer flushed in silence"
    "Witnesses are being compensated for their suffering"
    "Time slowed down to avoid accountability"
    "Memory suppression recommended"
    "The simulation logged out briefly"
    "Commit rejected: CRINGE violates repository ethics"
    "Merge conflict with dignity"
    "Rollback initiated to pre-cringe state"
    "CI pipeline failed at emotional validation stage"
    "Branch deleted for public safety"
    "CRINGE DLC installed successfully (no one asked for this)"
    "Achievement lost: Respect"
    "You have been rate-limited by social physics"
    "404: Aura not found"
    "CRINGE so dense it formed a support ticket"
    "Your diff has been rejected by peer review and God"
    "Stack trace points to: you"
    "NPC behavior detected. Skipping dialogue."
    "Touch grass command not found"
    "Aura: null"
    "This action cannot be undone. Neither can the shame."
  )
  
  print -P "\n%B%F{144}>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> $msg%f%b" | pv -qL 100
  [[ -f "$_VIBECHECK_DIR/ascii/soyjak.txt" ]] && cat "$_VIBECHECK_DIR/ascii/soyjak.txt"
  echo "${phrases[$((RANDOM % ${#phrases[@]} + 1))]}"
  
}

vibecheck() {
  (( RANDOM % 2 )) && based || cringe
}